### ISSUE TITLE
Error on selection English language

### ISSUE THREAD

**Issue by diegocanepa** [katherinepeterson/readme.so#124]
When I select English Langeage it doesn't change. The language setting stays in Spanish.
If you see the URL it doesn't change nither.
Can I fix it?

**Comment by diegocanepa** [comment]
https://user-images.githubusercontent.com/48829737/116630945-a19be080-a92a-11eb-8a15-2f9f670c0075.mp4

**Comment by waldyrious** [comment]
As a side note, this also reminds me of the argument in #93 (/cc @hey-fk): when someone is looking at a page in a given language (in this case, Spanish) and doesn't speak it, so they want to change to another language, the fact that the "language" label is localized will make this hard. For example, how should I know that "Dil" means "language" in Turkish?

IMO it would be more appropriate to use a language-indepenent symbol. For example:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Translation_-_Noun_project_987.svg/100px-Translation_-_Noun_project_987.svg.png)

or

![](https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Noun_Project_translation_icon_24074_cc.svg/144px-Noun_Project_translation_icon_24074_cc.svg.png)

@katherinepeterson should I open an issue?

**Comment by hey-fk** [comment]
@waldyrious I agree with you. It makes sense to use a lang-independent symbol.

@diegocanepa This is about the automatic detection of the language by browser as I have stated at #99 . English language address can be changed to /en in dropdown.

**Comment by diegocanepa** [comment]
@hey-fk Are you sure? I don't have the automatic detection of the language in my browser.
In addition, when I change de lenguegue, the tab is in english but not the page.
I think that the error come from  when you chosse the lenguague English the path is "/" and it have to be "/en".

**Comment by hey-fk** [comment]
@diegocanepa It is nextjs, not the browser which redirects automatically.
When you visit the website from "/" address, nextjs automatically detects the language and redirects from the browser language. 
When the "en" option is chosen under the dropdown english language address is not opening because of the english language address is "/". Then, the "/" address is being redirected automatically according to browser language by nextjs.
To turn it off, localeDetection must be set to false in the i18n setting or the url must be changed as "/en" instead of "/" for the english language that is under the dropdown. 

You may check this out of here:
https://nextjs.org/docs/advanced-features/i18n-routing#disabling-automatic-locale-detection
