### ISSUE TITLE
Allow importing an existing readme

### ISSUE THREAD

**Issue by katherinepeterson** [katherinepeterson/readme.so#14]
-user can upload an existing readme and edit 
- ideally we would parse the headers and create custom sections for what they already have

**Comment by rohitjmathew** [comment]
I felt it would be a great idea to be able to read readme's from github and maintain them here instead of importing them here. @katherinepeterson your thoughts on this?

**Comment by jai-dewani** [comment]
That's a great idea @rohitjmathew!! 
We can maybe allow the user to specify the repository link or the exact link to the readme file and it can be read and pre-set for them to edit and update `or` an elaborate setup can be to authorize the user via GitHub and extract readme's content from there but I feel like the former method can be implemented easily without any need for storing users data at our end

**Comment by rohitjmathew** [comment]
Agreed. The idea I had in mind is a common portal for all your readme based on an OAuth based GitHub login and access to all repos. We can them be able to edit them easily through the editor and push commits from here.

That said thats a big project and being able to import the raw README from GitHub is a much more simpler process right now.

**Comment by katherinepeterson** [comment]
I think we should keep it simple for the first iteration. Allow either uploading an `.md` file or a github link to the file

**Comment by rohitjmathew** [comment]
> I think we should keep it simple for the first iteration. Allow either uploading an `.md` file or a github link to the file

Agreed just felt I would add my long term thoughts here so we could keep that in mind and look at how to build towards a shared goal.

**Comment by jai-dewani** [comment]
Okay, I was actually thinking of how one would implement this. Fetching the readme is slightly tricky because the user can just pass the repositories link or the link to readme directly. After assessing what kind of link the user has entered, we can fetch the RAW .MD file by updating or altering the URL. 

### Example
`URL: https://github.com/remarkjs/remark/blob/main/readme.md`
If we update the `blob` to `raw` github throws back the raw content which can be easily extracted and set in the editor panel which would update the preview panel as well. 


### The bigger problem (according to me)
Is the `section` pane, as we would have to go through the readme and decide which all sections are already present and in which order and then update this to the `section` pane after a user imports their readme.

**Comment by jai-dewani** [comment]
Yeah, I didn't even think about the `H3` vs `H2` problem. This is turning out to be indeed a challenging feature.  
Yet this just motivates me even more to find an even more elegant solution to this problem 🤣
