### ISSUE TITLE
Full View of Editor 

### ISSUE THREAD

**Issue by jai-dewani** [katherinepeterson/readme.so#40]
As a user, I should be able to view the full readme at once in the editor pane if I want to instead of just separate sections. 

I suppose we can have one more item in the section tab named `Full View` (or something else, I am not good with naming :p) which would preview the whole readme in the Editor pane. 

I am not entirely sure how big of a task this would be or will need how the data is managed entirely but it feels like this should be possible and might increase user experience for the people who like having a full view before they download their hours of work creating an awesome readme 😉

**Comment by katherinepeterson** [comment]
@jai-dewani This is a good idea, maybe what we should do is have another tab on the right column that says "Raw" kind of like when you're viewing a markdown file on github. 

So the preview column would have 2 tabs: `rendered` and `raw` 

And we could allow a user to copy the raw text instead of downloading the file if they want

**Comment by jamesncox** [comment]
Forkin, cloning and creating a new branch "add-md-preview"
