### ISSUE TITLE
UI Bug: Section text should be left aligned when wrapped

### ISSUE THREAD

**Issue by katherinepeterson** [katherinepeterson/readme.so#49]
Currently the text in the section buttons is center aligned when it wraps, it should be left aligned

![Screen Shot 2021-04-13 at 8 38 29 PM](https://user-images.githubusercontent.com/49968061/114651167-4c0fd480-9c98-11eb-831b-75709d93d2b1.png)

**Comment by jai-dewani** [comment]
Hey @katherinepeterson I can't preproduce this problem in Microsoft Edge no matter how small I made the window, the min-width of the Section pane doesn't decreases. I am guessing the min-width is set so that all text comes in one line only because I tried adding more text but the section pane just expanded to include the text in one line 

![image](https://user-images.githubusercontent.com/33520257/114829405-a7e97300-9de8-11eb-855b-b02502684736.png)

**Comment by katherinepeterson** [comment]
@jai-dewani you're right, I think other design changes we made eliminated this bug. Closing this issue.
