### ISSUE TITLE
Saving state of user modified section data  to local-storage on browser refresh

### ISSUE THREAD

**Issue by saurabhchaturvedy** [katherinepeterson/readme.so#81]
@katherinepeterson , after we have basic PR merged for the local-storage , we need to make our section-slugs modifications also be refreshed and updated on browser refresh . Currently they pickup static data from section-templates.js

**Comment by katherinepeterson** [comment]
@saurabhchaturvedy the local-storage PR is merged if you want to work on this one

**Comment by saurabhchaturvedy** [comment]
@katherinepeterson Thanks a lot ! yes will work on this one to build upon the local-storage functionality .

**Comment by rohitjmathew** [comment]
I just used the functionality today and what i noticed was that i wanted to start afresh with a different readme but due to local storage the previous state with no data was being maintained. This was a hinderance that i had to delete all sections and start again. 

A button to reset state would be great if we want to go ahead with the same local storage approach

**Comment by saurabhchaturvedy** [comment]
@rohitjmathew ,you're right with the hinderance part & noticing that , i had  also raised the issue & PR  with changes for reset feature around 7 days back , it is yet to be reviewed and approved by @katherinepeterson . You can have a look at the feature at the deployed URL in this PR here #108  and provide your comments .
